# Generated by Django 4.2.7 on 2023-12-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_id', models.IntegerField()),
                ('Fname', models.CharField(max_length=50)),
                ('Lname', models.CharField(max_length=50)),
                ('Email_id', models.EmailField(max_length=50)),
                ('Contact', models.BigIntegerField()),
                ('Salary', models.IntegerField()),
                ('Location', models.CharField(max_length=50)),
            ],
        ),
    ]
